---
controllers:
  - SPARCControllerFilters.js
directives:
  - sparcModalFilterMore.js
  - sparcFilterCheckbox.js
  - sparcFilterRadio.js
  - sparcFilterSlider.js
  - sparcFilterContainer.js
templates:
  - modal/modal_filter_more.tpl.html
  - filter/filter_checkbox.tpl.html
  - filter/filter_radio.tpl.html
  - filter/filter_slider.tpl.html
  - filter_container.tpl.html
less:
  - filter.less
